### ISSUE TITLE
VersionConflict with nose on install

### ISSUE THREAD

**Issue by cadavor** [stratosinc/pygatt#23]
Hello,

When i try to install your script, I get this error : 
pkg_resources.VersionConflict: (nose 1.3.7 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('nose==1.3.1'))
Can you change your requirement ?

**Comment by peplin** [comment]
Hi there - you may want to use a [virtualenv](https://virtualenv.pypa.io/en/latest/) so the version of `nose` installed globally on your system doesn't conflict. We will probably update our nose version at some point, but in the meantime it shouldn't block you from installing.

**Comment by cadavor** [comment]
I'm on Rpi2 with Raspbian

Here the log : 
Downloading/unpacking pygatt[gatttool]
  Running setup.py egg_info for package pygatt
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/home/jeedom/build/pygatt/setup.py", line 54, in <module>
        include_package_data=True
      File "/usr/lib/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 221, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 245, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 588, in resolve
        raise VersionConflict(dist,req) # XXX put more info here
    pkg_resources.VersionConflict: (nose 1.3.7 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('nose==1.3.1'))
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/jeedom/build/pygatt/setup.py", line 54, in <module>

    include_package_data=True

  File "/usr/lib/python2.7/distutils/core.py", line 112, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 221, in __init__

    self.fetch_build_eggs(attrs.pop('setup_requires'))

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 245, in fetch_build_eggs

    parse_requirements(requires), installer=self.fetch_build_egg

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 588, in resolve

    raise VersionConflict(dist,req) # XXX put more info here

pkg_resources.VersionConflict: (nose 1.3.7 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('nose==1.3.1'))

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /home/jeedom/build/pygatt
Storing complete log in /home/jeedom/.pip/pip.log


Thanks for your help...

**Comment by peplin** [comment]
You may want to try out the `next` branch of this repository, I remember now we've actually dropped `nose` from the install dependencies.

**Comment by cadavor** [comment]
Sorry to ask that but how to use the next branch? (noob inside)

**Comment by stratosqa** [comment]
No problem, run "git checkout next" to switch branches

**Comment by cadavor** [comment]
Sorry, but after doing : 
pip install https://github.com/stratosinc/pygatt
I got that : 
pip install https://github.com/stratosinc/pygatt
Downloading/unpacking https://github.com/stratosinc/pygatt
  Downloading pygatt (unknown size): 55Kb downloaded
  Cannot unpack file /tmp/pip-ryy7Dt-unpack/pygatt (downloaded from /tmp/pip-x_XHGC-build, content-type: text/html; charset=utf-8); cannot detect archive format
Cannot determine archive format of /tmp/pip-x_XHGC-build
Storing complete log in /home/jeedom/.pip/pip.log

I think i've got a problem firstly here no?

Thanks for your help

**Comment by stratosqa** [comment]
Try this:

pip install "git+https://github.com/stratosinc/pygatt@next"

**Comment by cadavor** [comment]
Do not take care about my previous message (if you've read it)...

To solve the problem, I've forced installation of nose 1.3.1. (sudo pip install nose==1.3.1)
And coverage 3.7.1 and the installation complete...

**Comment by peplin** [comment]
OK, great!

**Comment by cadavor** [comment]
Thanks for your help.
